// CERTIFICATIONS HUB data. To add another certification, push another object into COURSE.certs.
// Exam facts and domain names/weights come from claudecertificationguide.com/learn (Exam Guide v1.0, July 2026).
// The topic breakdown under each domain is this site's own study checklist, built from those focus areas.
window.COURSE.certs = [
  {
    id: 'ccarf',
    code: 'CCAR-F',
    name: 'Claude Certified Architect – Foundations',
    emoji: '🎓',
    blurb: 'Design and build production systems with Claude: agents, tools, MCP, Claude Code, prompts and reliability.',
    facts: [
      ['Questions', '60'], ['Time', '120 minutes'], ['Passing score', '720 / 1000 (about 72%)'],
      ['Cost', '$125 USD'], ['Valid for', '12 months'], ['Delivery', 'Pearson VUE (online proctored or test centre)'],
    ],
    note: 'Source: claudecertificationguide.com (Exam Guide v1.0, July 2026). Rules, prices and weights can change, so confirm on the official exam page before you book.',
    domains: [
      { id: 'd1', n: 1, name: 'Agentic Architecture & Orchestration', weight: 27, emoji: '🕸️',
        focus: 'Design and implement agentic systems with the Claude API: loop management, orchestration patterns, guardrails, Claude Agent SDK.',
        lessons: ['c4', 'c3', 'c8', 'c11'],
        topics: [
          'Workflow vs agent: when to use which (start simple)',
          'The agentic loop: stop_reason, tool_use, tool_result, end_turn',
          'The six patterns: chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer, autonomous agent',
          'Sub-agents: context isolation, briefs, returning summaries',
          'Loop management: max turns, token/time/cost budgets, stop conditions, loop detection',
          'Guardrails: input/output validation, least privilege, human approval, sandboxing',
          'Prompt injection and the lethal trifecta',
          'Claude Agent SDK: query loop, built-in tools, permissions, hooks, subagents, sessions',
          'State, memory and checkpoints for long-running agents',
          'Error handling, retries, idempotency and escalation to humans',
          'Observability: logging, tracing and cost tracking for agent runs',
        ] },
      { id: 'd2', n: 2, name: 'Tool Design & MCP Integration', weight: 18, emoji: '🔌',
        focus: 'Effective tool schema design, MCP server and client implementation, integrating external services.',
        lessons: ['c3', 'c7'],
        topics: [
          'Tool anatomy: name, description, input_schema',
          'Writing descriptions: what, when to use, when not to use, argument formats',
          'Schema design: enums, required fields, nullable, constraints',
          'tool_choice: auto, any, tool, none',
          'Parallel tool calls and returning all tool_results together',
          'Tool errors: is_error and actionable messages',
          'Granularity: narrow tools vs generic ones; how many tools is too many',
          'Idempotency, validation and least-privilege for tools',
          'MCP architecture: host/client/server',
          'MCP primitives: tools, resources, prompts',
          'MCP transports (stdio, streamable HTTP) and authentication',
          'Building and registering an MCP server; .mcp.json and scopes',
          'MCP security: untrusted servers, tool poisoning, approvals',
          'Result size, pagination and concise responses',
        ] },
      { id: 'd3', n: 3, name: 'Claude Code Configuration & Workflows', weight: 20, emoji: '💻',
        focus: 'Development workflow configuration, settings and hooks, permissions, CI/CD pipeline integration.',
        lessons: ['c9', 'c12', 'c7'],
        topics: [
          'CLAUDE.md: purpose, hierarchy (user, project, subdirectory), what belongs in it',
          'settings.json files and their scopes (user, project, local)',
          'Permissions: allow, deny, ask rules and permission modes',
          'Hooks: events (PreToolUse, PostToolUse, Stop...), matchers, blocking with exit codes',
          'Skills: SKILL.md and when they load',
          'Subagents and slash commands',
          'Plan mode and the explore, plan, implement, verify workflow',
          'MCP servers inside Claude Code',
          'Managing context: /clear, /compact, keeping sessions focused',
          'Headless mode (claude -p) and output formats for automation',
          'CI/CD: GitHub Actions integration, secrets, least-privilege tokens, cost caps',
          'Safe automation: never auto-merge, human review, sandboxed runners',
        ] },
      { id: 'd4', n: 4, name: 'Prompt Engineering & Structured Output', weight: 20, emoji: '✍️',
        focus: 'Effective prompt crafting, structured output patterns, production-level prompt engineering.',
        lessons: ['c1', 'c2', 'c8'],
        topics: [
          'Messages API anatomy: roles, system prompt, max_tokens, temperature, stop_reason',
          'Clear and explicit instructions: audience, format, length, tone',
          'Explaining the why behind rules',
          'XML tags to separate instructions and data',
          'Few-shot examples',
          'Letting the model reason first (thinking, then answer)',
          'Giving an out: "not found" / "unknown" handling',
          'Structured output via forced tool use + JSON schema',
          'Schema design: enums, nullable fields, field order, descriptions',
          'Validation and retry-with-feedback loops',
          'Production prompting: templates, versioning, evals before and after changes',
          'Prompt-injection resistance in prompts',
        ] },
      { id: 'd5', n: 5, name: 'Context Management & Reliability', weight: 15, emoji: '💰',
        focus: 'Context window optimisation, caching strategy, long conversations, reliable production system design.',
        lessons: ['c5', 'c6', 'c8'],
        topics: [
          'Context window basics and token budgeting',
          'Prompt caching: cache_control, stable prefix first, reading the usage fields',
          'Long conversations: summarising, compaction, clearing old tool results',
          'Memory outside the window: files, notes, databases',
          'RAG: chunking, embeddings, hybrid search, reranking, citations',
          'Evaluating RAG: retrieval vs generation',
          'Cost and latency: model routing, batch API, streaming',
          'Reliability: retries with backoff and jitter, timeouts, fallbacks',
          'Evals: datasets, code graders, LLM-as-judge, regression checks',
          'Monitoring and observability in production',
        ] },
    ],
  },
];
